name: bak

permissions:
  contents: write

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    # 分钟 小时 日期 月份 星期（0-6）//0代表星期天
    - cron: "1 0 * * *"
  push:
    branches: [main]
    paths:
      - ".github/workflows/bak.yml"
      - ".github/workflows/cron.yml"

jobs:
  run:
    uses: ./.github/workflows/cron.yml
    with:
      name: bak
    secrets: inherit
