name: cname_flatten

env:
  TZ: Asia/Shanghai

on:
  workflow_dispatch:
  schedule:
    # 分钟 小时 日期 月份 星期（0-6）//0代表星期天
    - cron: "*/5 * * * *"
  push:
    branches: [main]
    paths:
      - ".github/workflows/cname_flatten.yml"
      - ".github/workflows/cron.yml"

jobs:
  run:
    uses: ./.github/workflows/cron.yml
    with:
      name: cname_flatten
    secrets: inherit
